# Generated by Django 5.0.4 on 2024-05-01 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0002_alter_book_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='edad')),
            ],
            options={
                'verbose_name': 'Lector',
                'verbose_name_plural': 'Lectores',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_loan', models.DateField(verbose_name='Fecha De Prestamo')),
                ('date_return', models.DateField(blank=True, null=True, verbose_name='Fecha De Devolucion')),
                ('bookReturn', models.BooleanField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lector.reader')),
            ],
            options={
                'verbose_name': 'Prestamos',
                'verbose_name_plural': 'Prestamos',
            },
        ),
    ]
