# Generated by Django 5.0.4 on 2024-05-04 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Prestamo', 'verbose_name_plural': 'Prestamos'},
        ),
    ]
