# Generated by Django 5.0.4 on 2024-04-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('age', models.PositiveIntegerField(verbose_name='Edad')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autoress',
            },
        ),
    ]
