# Generated by Django 5.0.4 on 2024-05-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AddField(
            model_name='book',
            name='background',
            field=models.ImageField(default=None, upload_to='media/book', verbose_name='Imagen De Portada'),
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(default=None, verbose_name='Fecha De Lanzamiento'),
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(max_length=30, verbose_name='Libro'),
        ),
    ]
