# Generated by Django 5.0.4 on 2024-05-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_alter_book_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='book',
            name='background',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/book', verbose_name='Imagen De Portada'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(blank=None, default=None, verbose_name='Fecha De Lanzamiento'),
        ),
        migrations.AlterField(
            model_name='book',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(max_length=30, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='libro.category'),
        ),
    ]
