# Generated by Django 5.0.4 on 2024-05-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0007_alter_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='category_authors', to='libro.category'),
        ),
    ]
