# Generated by Django 5.0.4 on 2024-05-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autor", "0002_alter_author_options"),
        ("libro", "0019_alter_book_authors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="authors",
        ),
        migrations.AlterField(
            model_name="book",
            name="background",
            field=models.ImageField(
                blank=True,
                default=True,
                null=True,
                upload_to="media/book",
                verbose_name="Imagen De Portada",
            ),
        ),
        migrations.RemoveField(
            model_name="book",
            name="category",
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                related_name="categoria_libro", to="autor.author"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ManyToManyField(
                related_name="categoria_libro", to="libro.category"
            ),
        ),
    ]
