# Generated by Django 5.0.4 on 2024-05-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0022_alter_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='categoria_libro', to='libro.category'),
        ),
    ]
