# Generated by Django 5.0.4 on 2024-05-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0024_remove_book_category_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='background',
            field=models.ImageField(blank=True, default=True, upload_to='media/book', verbose_name='Imagen De Portada'),
        ),
    ]
