# Generated by Django 5.0.4 on 2024-05-04 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0026_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='background',
            field=models.ImageField(blank=True, default=None, upload_to='media/book', verbose_name='Imagen De Portada'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_libro', to='libro.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(default=None, verbose_name='Fecha De Lanzamiento'),
        ),
    ]
